adding common html partial for all pages, added css, tweaked gitignore
DumplingLTD/ExceptionNull pull request #12
Opened 2017-04-10 21:21 UTC by jli227

Added Pebble Extension to support global variables for templates
Added common.html partial for all pages
Added CSS temporary SCSS for consistency
Added CSS to .gitignore because SCSS handles generation

2017-04-10 22:05 UTC, fru1tstand requested changes

2017-04-10 22:05 UTC, fru1tstand commented on src/main/java/com/jonathanpli/ExceptionNullApplication.java
> +		PebbleEngine.Builder builder = new PebbleEngine.Builder().extension(new PebbleExtension())
For all chained methods on a builder, please make newlines. This helps readability.
```
new PebbleEngine.Builder()
    .extension(...)
    .loader(...)
```

2017-04-10 22:05 UTC, fru1tstand commented on src/main/java/com/jonathanpli/exceptionnull/controller/helpers/PebbleExtension.java
> + * Created by Jonathan on 4/9/17.
Please javadoc and include what the extension does/provides. Up to you to `@author`, but I personally don't add the tag.

2017-04-10 22:05 UTC, fru1tstand commented on src/main/java/com/jonathanpli/exceptionnull/controller/helpers/PebbleExtension.java
> +        globals.put("paths", getPaths());
Is this intentional? Every call to #getGlobalVariables() will put getPaths() into the globals map.

2017-04-10 22:05 UTC, fru1tstand commented on src/main/java/com/jonathanpli/exceptionnull/controller/helpers/PebbleExtension.java
> +        String[][] paths = {
Consider using [ImmutableList.of(T...)](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/ImmutableList.html#of-E-), and making into a constant.

2017-04-10 22:05 UTC, fru1tstand commented on src/main/resources/templates/common.html
> +</html>
nit: Please add a newline at the end of files

2017-04-10 22:05 UTC, fru1tstand commented on src/main/resources/templates/index.html
> +{% endblock %}
nit: newline

2017-04-10 22:05 UTC, fru1tstand commented on src/main/scss/styles.scss
> +$primary-font: "Helvetica Neue", "Open Sans", sans-serif;
Please create a new scss partial file named "_variables.scss" and `@import 'variables'` at the top of this file. Move these variables into that file.

2017-04-10 22:05 UTC, fru1tstand commented on src/main/scss/styles.scss
> +	border-bottom: 1px solid #C3C3C3;
Colors should never be hard coded. Use variables instead.

2017-04-10 22:05 UTC, fru1tstand commented on src/main/scss/styles.scss
> +}
nit: newline

2017-04-10 22:05 UTC, fru1tstand commented on src/main/resources/templates/common.html
> +<!DOCTYPE html>
We should comment template files with their function. For example "The main entrypoint used as a basis for all pages"

2017-04-10 22:05 UTC, fru1tstand commented on src/main/resources/templates/index.html
> +{% extends "common" %}
Please comment and note if this is a directly accessible page, or another template file.

2017-04-10 22:05 UTC, fru1tstand commented on src/main/java/com/jonathanpli/exceptionnull/controller/helpers/PebbleExtension.java
> +    private Map<String, Object> globals;
Consider using [ImmutableMap<K, V>](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/ImmutableMap.html).

2017-04-12 21:49 UTC, jli227 commented on src/main/java/com/jonathanpli/exceptionnull/controller/helpers/PebbleExtension.java
> +        String[][] paths = {
Leaving as is for now, as Pebble's "for" loop isn't working as expected (as specified in documentation). Will figure out solution for future commit

2017-04-12 21:49 UTC, jli227 commented on src/main/resources/templates/common.html
> +<!DOCTYPE html>
Added

2017-04-12 21:49 UTC, jli227 commented on src/main/resources/templates/common.html
> +</html>
Added

2017-04-12 21:49 UTC, jli227 commented on src/main/resources/templates/index.html
> +{% endblock %}
Added

2017-04-12 23:20 UTC, fru1tstand requested changes
Good. Please be sure to respond to all comments made. If it's a simple fix, feel free to just respond "done".

2017-04-12 23:20 UTC, fru1tstand commented on src/main/java/com/jonathanpli/exceptionnull/controller/helpers/PebbleExtension.java
> +        String[][] paths = {
Please then add a `// TODO(jonathan): ...`

2017-04-12 23:20 UTC, fru1tstand commented on src/main/scss/styles.scss
> +@import '_variables';
No need to include the underscore when [importing](http://sass-lang.com/guide#topic-5).

2017-04-12 23:20 UTC, fru1tstand commented on src/main/scss/styles.scss
> +	border-bottom: 1px solid $gray-border;
Up to you, feel free to do the following in _variables.scss:
```
$color-accent: <the grey color>;

$header-border-color: $color-accent;
$footer-border-color: $color-accent;
```
And modify the variable usage in this file accordingly.

2017-04-14 04:59 UTC, jli227 commented on src/main/scss/styles.scss
> +	border-bottom: 1px solid $gray-border;
done

2017-04-14 04:59 UTC, jli227 commented on src/main/scss/styles.scss
> +@import '_variables';
done

2017-04-14 04:59 UTC, jli227 commented on src/main/java/com/jonathanpli/exceptionnull/controller/helpers/PebbleExtension.java
> +        String[][] paths = {
done

2017-04-14 08:51 UTC, fru1tstand reviewed
Please be sure to review and respond to all "outdated" comments. They're only visible on the "Conversation" tab for some reason.

2017-04-17 21:33 UTC, jli227 commented on src/main/java/com/jonathanpli/ExceptionNullApplication.java
> +		PebbleEngine.Builder builder = new PebbleEngine.Builder().extension(new PebbleExtension())
done

2017-04-17 21:33 UTC, jli227 commented on src/main/java/com/jonathanpli/exceptionnull/controller/helpers/PebbleExtension.java
> + * Created by Jonathan on 4/9/17.
done

2017-04-17 21:33 UTC, jli227 commented on src/main/java/com/jonathanpli/exceptionnull/controller/helpers/PebbleExtension.java
> +    private Map<String, Object> globals;
done

2017-04-17 21:33 UTC, jli227 commented on src/main/java/com/jonathanpli/exceptionnull/controller/helpers/PebbleExtension.java
> +        globals.put("paths", getPaths());
done

2017-04-17 21:41 UTC, fru1tstand approved these changes

2017-04-17 21:49 UTC, merged