Completed Challenge and Review Pages to Final Form
DumplingLTD/ExceptionNull pull request #40
Opened 2017-05-25 06:23 UTC by fru1tstand

+ Added mock challenge question
+ Completed live syntax highlighting "within" textarea
+ Added review code commenting
+ Wired score metric assignment

2017-05-25 06:26 UTC, fru1tstand commented
Finishes #29

2017-05-25 08:49 UTC, jonathanpli requested changes

2017-05-25 08:49 UTC, jli227 commented on src/main/resources/templates/challenge.html
> +import java.lang.reflect.AnnotatedElement;
Not sure how to request a change for this, but when looking at the front end, if I try interacting with the code, a bunch of the code in the challenge shows up with red underline, even though the package imports look correct. Would you happen to know how to fix that?

2017-05-25 08:55 UTC, fru1tstand commented on src/main/resources/templates/challenge.html
> +import java.lang.reflect.AnnotatedElement;
Yeah, it's the browser's autocorrect. Good catch.

2017-05-25 09:01 UTC, jonathanpli requested changes

2017-05-25 09:01 UTC, jli227 commented on src/main/resources/templates/challenge.html
> +import java.lang.reflect.AnnotatedElement;
Cool! Seemed to fix most of the problems. There are still some red underlining, but here's an interesting one -- 
<img width="1092" alt="screen shot 2017-05-25 at 1 58 56 am" src="https://cloud.githubusercontent.com/assets/13812345/26443557/c6bc6eb0-40ed-11e7-97bb-2298c6e62415.png">

So there's the red underline, but if I try deleting one character, this is what happens --
<img width="1076" alt="screen shot 2017-05-25 at 1 59 53 am" src="https://cloud.githubusercontent.com/assets/13812345/26443579/e201f4ba-40ed-11e7-8498-0e3543aa7b2d.png">

2017-05-25 09:07 UTC, fru1tstand commented on src/main/resources/templates/challenge.html
> +import java.lang.reflect.AnnotatedElement;
I didn't push to the server, but can you highlight the part that's underlined and screenshot it again? The way it's set up is a <textarea> is laying over the <pre><code> block and the styles between the two should match exactly. The textarea is providing the ability to edit, show a caret, and highlight (not color, think copy/paste type of highlight) text, and the pre/code block is there to provide the syntax highlighting. The underlining of what appears to be blank space may be caused by the two not aligning properly.

2017-05-25 09:38 UTC, jli227 commented on src/main/resources/templates/challenge.html
> +import java.lang.reflect.AnnotatedElement;
Here's the text alignment problem--the red underline is gone now, interestingly enough.

<img width="447" alt="screen shot 2017-05-25 at 2 37 22 am" src="https://cloud.githubusercontent.com/assets/13812345/26444914/20196940-40f3-11e7-9fd4-3c2412f5f4f0.png">

2017-05-25 19:28 UTC, fru1tstand commented on src/main/resources/templates/challenge.html
> +import java.lang.reflect.AnnotatedElement;
I pushed to the server which removed all underlining. I also fixed the text collapse on all major browsers except IE. IE will never stop softwrapping the textarea which is throwing the alignment off. For now, I don't think I want to invest any more time into the issue as there are more important things than getting IE compliance.

2017-05-26 10:39 UTC, jonathanpli approved these changes

2017-05-26 10:39 UTC, jli227 commented on src/main/resources/templates/challenge.html
> +import java.lang.reflect.AnnotatedElement;
All of the underlining is gone (yay!), but the text alignment issue is still there for my smaller screen on Chrome, even after doing a hard cache refresh. Assuming we'll be using a larger monitor for the demo, and it doesn't affect the demo, though, I think it's fine to ignore the problem for now.

![image](https://cloud.githubusercontent.com/assets/13812345/26491508/cb06cd4e-41c4-11e7-9153-a27dd530809d.png)

2017-05-26 19:31 UTC, merged